// ============================================================
// COLLEGIA — Development Seed Dataset
//
// IMPORTANT: This is DEMO / DEVELOPMENT data. Values are
// realistic-looking placeholders intended for building and
// testing the product. They are NOT verified admissions
// statistics and must never be presented as real.
//
// Every record seeds with isDemoData=true and
// verificationStatus=DEMO so real sourced data can replace
// these records later without ambiguity.
// ============================================================

export interface SeedCollege {
  name: string;
  slug: string;
  shortName?: string;
  city: string;
  state: string;
  stateCode: string;
  region: "NORTHEAST" | "EAST_COAST" | "MIDWEST" | "SOUTH" | "SOUTHWEST" | "WEST_COAST";
  type: "PUBLIC" | "PRIVATE";
  setting: "URBAN" | "SUBURBAN" | "RURAL";
  sizeCategory: "SMALL" | "MEDIUM" | "LARGE";
  undergradEnrollment: number;
  acceptanceRate: number; // 0-100, demo
  avgGpa: number; // unweighted, demo
  satRange: [number, number];
  actRange: [number, number];
  graduationRate: number; // 0-100, demo
  studentFacultyRatio: string;
  tuitionInState?: number;
  tuitionOutOfState?: number;
  tuitionInternational: number;
  roomAndBoard: number;
  estimatedTotalCost?: number;
  intlAid: boolean;
  meritScholarships?: boolean;
  needBasedAid?: boolean;
  meetsFullNeed?: boolean;
  avgAid?: number;
  intlPercentage: number; // 0-100, demo
  intlPopulation?: number;
  toeflMin?: number;
  ieltsMin?: number;
  housing?: string;
  clubs?: number;
  sports?: string[];
  greekLife?: boolean;
  website?: string;
  image: string;
  tags: string[];
  featured?: boolean;
  strongPrograms: string[];
  earlyAction?: string; // "MM-DD"
  earlyDecision?: string;
  regularDecision?: string; // "MM-DD"
  rolling?: boolean;
}

const IMG = {
  boston: "/images/campus_boston.jpg",
  florida: "/images/campus_florida.jpg",
  nyc: "/images/campus_nyc.jpg",
  california: "/images/campus_california.jpg",
  hero: "/images/hero_campus.jpg",
};

export const seedColleges: SeedCollege[] = [
  // ============================================================
  // NORTHEAST — highly selective
  // ============================================================
  {
    name: "Boston College", slug: "boston-college", shortName: "BC",
    city: "Chestnut Hill", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 9800,
    acceptanceRate: 19, avgGpa: 3.9, satRange: [1390, 1530], actRange: [33, 35],
    graduationRate: 92, studentFacultyRatio: "13:1",
    tuitionInternational: 62000, roomAndBoard: 16800, estimatedTotalCost: 78800,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: true, avgAid: 38000,
    intlPercentage: 12, intlPopulation: 1200, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 230, sports: ["Football", "Basketball", "Soccer", "Hockey"], greekLife: false,
    website: "https://www.bc.edu", image: IMG.boston,
    tags: ["Research", "Jesuit", "Division I", "Need-Blind"], featured: true,
    strongPrograms: ["Business", "Engineering", "Nursing", "Philosophy", "Economics"],
    earlyAction: "11-01", regularDecision: "01-01",
  },
  {
    name: "Harvard University", slug: "harvard-university", shortName: "Harvard",
    city: "Cambridge", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7100,
    acceptanceRate: 3.5, avgGpa: 4.0, satRange: [1470, 1580], actRange: [34, 36],
    graduationRate: 97, studentFacultyRatio: "7:1",
    tuitionInternational: 57500, roomAndBoard: 20200, estimatedTotalCost: 77700,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 66000,
    intlPercentage: 14, intlPopulation: 1000, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 450, sports: ["Crew", "Basketball", "Football", "Soccer"], greekLife: false,
    website: "https://www.harvard.edu", image: IMG.boston,
    tags: ["Ivy League", "Research", "Need-Blind", "Global"],
    strongPrograms: ["Computer Science", "Economics", "Political Science", "Biology", "Mathematics"],
    earlyAction: "11-01", regularDecision: "01-01",
  },
  {
    name: "MIT", slug: "massachusetts-institute-of-technology", shortName: "MIT",
    city: "Cambridge", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 4600,
    acceptanceRate: 4, avgGpa: 4.0, satRange: [1520, 1580], actRange: [35, 36],
    graduationRate: 95, studentFacultyRatio: "3:1",
    tuitionInternational: 59900, roomAndBoard: 19000, estimatedTotalCost: 78900,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 58000,
    intlPercentage: 10, intlPopulation: 460, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 500, sports: ["Crew", "Basketball", "Swimming", "Soccer"], greekLife: false,
    website: "https://web.mit.edu", image: IMG.boston,
    tags: ["STEM", "Research", "Need-Blind", "Engineering"],
    strongPrograms: ["Computer Science", "Mechanical Engineering", "Electrical Engineering", "Physics", "Mathematics"],
    earlyAction: "11-01", regularDecision: "01-01",
  },
  {
    name: "Columbia University", slug: "columbia-university", shortName: "Columbia",
    city: "New York", state: "New York", stateCode: "NY", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 8900,
    acceptanceRate: 4.1, avgGpa: 3.95, satRange: [1490, 1570], actRange: [34, 35],
    graduationRate: 96, studentFacultyRatio: "6:1",
    tuitionInternational: 66000, roomAndBoard: 18600, estimatedTotalCost: 84600,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 63000,
    intlPercentage: 20, intlPopulation: 1780, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 500, sports: ["Fencing", "Basketball", "Football", "Tennis"], greekLife: false,
    website: "https://www.columbia.edu", image: IMG.nyc,
    tags: ["Ivy League", "Urban", "Research", "Need-Blind"],
    strongPrograms: ["Computer Science", "Economics", "Political Science", "Film", "Philosophy"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "New York University", slug: "new-york-university", shortName: "NYU",
    city: "New York", state: "New York", stateCode: "NY", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 27700,
    acceptanceRate: 12, avgGpa: 3.9, satRange: [1370, 1540], actRange: [31, 35],
    graduationRate: 85, studentFacultyRatio: "10:1",
    tuitionInternational: 60000, roomAndBoard: 21000, estimatedTotalCost: 81000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 22000,
    intlPercentage: 24, intlPopulation: 6650, toeflMin: 100, ieltsMin: 7.5,
    housing: "Available all years", clubs: 500, sports: ["Basketball", "Fencing", "Swimming", "Tennis"], greekLife: false,
    website: "https://www.nyu.edu", image: IMG.nyc,
    tags: ["Global", "Urban", "Arts", "Research"], featured: true,
    strongPrograms: ["Film", "Business", "Economics", "Computer Science", "Communications"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Cornell University", slug: "cornell-university", shortName: "Cornell",
    city: "Ithaca", state: "New York", stateCode: "NY", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 15700,
    acceptanceRate: 8.7, avgGpa: 3.9, satRange: [1470, 1560], actRange: [33, 35],
    graduationRate: 94, studentFacultyRatio: "9:1",
    tuitionInternational: 66000, roomAndBoard: 18000, estimatedTotalCost: 84000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 51000,
    intlPercentage: 12, intlPopulation: 1880, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 1000, sports: ["Football", "Basketball", "Soccer", "Hockey"], greekLife: false,
    website: "https://www.cornell.edu", image: IMG.boston,
    tags: ["Ivy League", "Research", "Engineering", "Agriculture"],
    strongPrograms: ["Engineering", "Agriculture", "Computer Science", "Business", "Architecture"],
    earlyDecision: "11-01", regularDecision: "01-02",
  },
  {
    name: "University of Pennsylvania", slug: "university-of-pennsylvania", shortName: "Penn",
    city: "Philadelphia", state: "Pennsylvania", stateCode: "PA", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 10400,
    acceptanceRate: 6.5, avgGpa: 3.95, satRange: [1490, 1570], actRange: [34, 36],
    graduationRate: 96, studentFacultyRatio: "6:1",
    tuitionInternational: 64000, roomAndBoard: 17800, estimatedTotalCost: 81800,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 58000,
    intlPercentage: 16, intlPopulation: 1660, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 600, sports: ["Basketball", "Football", "Swimming", "Soccer"], greekLife: true,
    website: "https://www.upenn.edu", image: IMG.nyc,
    tags: ["Ivy League", "Research", "Business", "Pre-Medicine"],
    strongPrograms: ["Business", "Economics", "Nursing", "Pre-Medicine", "Computer Science"],
    earlyDecision: "11-01", regularDecision: "01-05",
  },
  {
    name: "Princeton University", slug: "princeton-university", shortName: "Princeton",
    city: "Princeton", state: "New Jersey", stateCode: "NJ", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 5300,
    acceptanceRate: 4.6, avgGpa: 4.0, satRange: [1510, 1570], actRange: [34, 35],
    graduationRate: 98, studentFacultyRatio: "5:1",
    tuitionInternational: 59000, roomAndBoard: 19800, estimatedTotalCost: 78800,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 68000,
    intlPercentage: 14, intlPopulation: 740, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 300, sports: ["Crew", "Basketball", "Soccer", "Squash"], greekLife: false,
    website: "https://www.princeton.edu", image: IMG.boston,
    tags: ["Ivy League", "Research", "Need-Blind", "Liberal Arts"],
    strongPrograms: ["Computer Science", "Economics", "Mathematics", "Philosophy", "Political Science"],
    earlyAction: "11-01", regularDecision: "01-01",
  },
  {
    name: "Yale University", slug: "yale-university", shortName: "Yale",
    city: "New Haven", state: "Connecticut", stateCode: "CT", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 6500,
    acceptanceRate: 5, avgGpa: 4.0, satRange: [1500, 1580], actRange: [34, 35],
    graduationRate: 97, studentFacultyRatio: "6:1",
    tuitionInternational: 64000, roomAndBoard: 19000, estimatedTotalCost: 83000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 66000,
    intlPercentage: 13, intlPopulation: 850, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 400, sports: ["Crew", "Football", "Basketball", "Soccer"], greekLife: false,
    website: "https://www.yale.edu", image: IMG.nyc,
    tags: ["Ivy League", "Research", "Need-Blind", "Global"],
    strongPrograms: ["Economics", "Political Science", "History", "Computer Science", "Psychology"],
    earlyAction: "11-01", regularDecision: "01-02",
  },
  {
    name: "Brown University", slug: "brown-university", shortName: "Brown",
    city: "Providence", state: "Rhode Island", stateCode: "RI", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7200,
    acceptanceRate: 5.5, avgGpa: 3.95, satRange: [1490, 1570], actRange: [34, 36],
    graduationRate: 96, studentFacultyRatio: "6:1",
    tuitionInternational: 65000, roomAndBoard: 17300, estimatedTotalCost: 82300,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 59000,
    intlPercentage: 14, intlPopulation: 1010, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 500, sports: ["Crew", "Basketball", "Soccer", "Tennis"], greekLife: false,
    website: "https://www.brown.edu", image: IMG.boston,
    tags: ["Ivy League", "Open Curriculum", "Research", "Arts"],
    strongPrograms: ["Computer Science", "Film", "Biology", "Economics", "Neuroscience"],
    earlyDecision: "11-01", regularDecision: "01-05",
  },
  {
    name: "Dartmouth College", slug: "dartmouth-college", shortName: "Dartmouth",
    city: "Hanover", state: "New Hampshire", stateCode: "NH", region: "NORTHEAST",
    type: "PRIVATE", setting: "RURAL", sizeCategory: "SMALL", undergradEnrollment: 4400,
    acceptanceRate: 6.4, avgGpa: 3.95, satRange: [1490, 1570], actRange: [34, 35],
    graduationRate: 95, studentFacultyRatio: "7:1",
    tuitionInternational: 62000, roomAndBoard: 18600, estimatedTotalCost: 80600,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 61000,
    intlPercentage: 16, intlPopulation: 700, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 250, sports: ["Skiing", "Football", "Basketball", "Ice Hockey"], greekLife: true,
    website: "https://home.dartmouth.edu", image: IMG.hero,
    tags: ["Ivy League", "Liberal Arts", "Outdoor", "Research"],
    strongPrograms: ["Economics", "Computer Science", "Government", "Engineering", "Environmental Science"],
    earlyDecision: "11-01", regularDecision: "01-02",
  },
  {
    name: "Georgetown University", slug: "georgetown-university", shortName: "Georgetown",
    city: "Washington", state: "District of Columbia", stateCode: "DC", region: "EAST_COAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7300,
    acceptanceRate: 12, avgGpa: 3.9, satRange: [1410, 1540], actRange: [32, 35],
    graduationRate: 95, studentFacultyRatio: "11:1",
    tuitionInternational: 64000, roomAndBoard: 18500, estimatedTotalCost: 82500,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 28000,
    intlPercentage: 13, intlPopulation: 950, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 3 years", clubs: 200, sports: ["Basketball", "Soccer", "Lacrosse", "Sailing"], greekLife: false,
    website: "https://www.georgetown.edu", image: IMG.nyc,
    tags: ["Jesuit", "Policy", "International Relations", "Research"],
    strongPrograms: ["International Relations", "Political Science", "Economics", "Business", "Law"],
    earlyAction: "11-01", regularDecision: "01-10",
  },
  {
    name: "Johns Hopkins University", slug: "johns-hopkins-university", shortName: "JHU",
    city: "Baltimore", state: "Maryland", stateCode: "MD", region: "EAST_COAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 6100,
    acceptanceRate: 7.6, avgGpa: 3.95, satRange: [1520, 1570], actRange: [34, 36],
    graduationRate: 94, studentFacultyRatio: "6:1",
    tuitionInternational: 63000, roomAndBoard: 17700, estimatedTotalCost: 80700,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 55000,
    intlPercentage: 16, intlPopulation: 980, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 400, sports: ["Lacrosse", "Basketball", "Soccer", "Swimming"], greekLife: true,
    website: "https://www.jhu.edu", image: IMG.hero,
    tags: ["Research", "Medical", "STEM", "Pre-Medicine"],
    strongPrograms: ["Pre-Medicine", "Public Health", "Neuroscience", "Biomedical Engineering", "Computer Science"],
    earlyDecision: "11-01", regularDecision: "01-02",
  },
  {
    name: "Carnegie Mellon University", slug: "carnegie-mellon-university", shortName: "CMU",
    city: "Pittsburgh", state: "Pennsylvania", stateCode: "PA", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7400,
    acceptanceRate: 14, avgGpa: 3.9, satRange: [1490, 1560], actRange: [34, 35],
    graduationRate: 92, studentFacultyRatio: "10:1",
    tuitionInternational: 61000, roomAndBoard: 15600, estimatedTotalCost: 76600,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 33000,
    intlPercentage: 25, intlPopulation: 1850, toeflMin: 102, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 300, sports: ["Basketball", "Soccer", "Tennis", "Swimming"], greekLife: true,
    website: "https://www.cmu.edu", image: IMG.hero,
    tags: ["STEM", "Engineering", "Computer Science", "Arts"],
    strongPrograms: ["Computer Science", "Electrical Engineering", "Business", "Fine Arts", "Data Science"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Tufts University", slug: "tufts-university", shortName: "Tufts",
    city: "Medford", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 6800,
    acceptanceRate: 11, avgGpa: 3.9, satRange: [1450, 1530], actRange: [33, 35],
    graduationRate: 93, studentFacultyRatio: "10:1",
    tuitionInternational: 64000, roomAndBoard: 16000, estimatedTotalCost: 80000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: false, avgAid: 36000,
    intlPercentage: 13, intlPopulation: 880, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 300, sports: ["Basketball", "Soccer", "Lacrosse", "Swimming"], greekLife: true,
    website: "https://www.tufts.edu", image: IMG.boston,
    tags: ["Research", "Pre-Medicine", "International Relations", "Liberal Arts"],
    strongPrograms: ["International Relations", "Pre-Medicine", "Computer Science", "Psychology", "Engineering"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Boston University", slug: "boston-university", shortName: "BU",
    city: "Boston", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 18500,
    acceptanceRate: 14, avgGpa: 3.85, satRange: [1360, 1480], actRange: [31, 34],
    graduationRate: 89, studentFacultyRatio: "11:1",
    tuitionInternational: 62000, roomAndBoard: 19000, estimatedTotalCost: 81000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 26000,
    intlPercentage: 24, intlPopulation: 4440, toeflMin: 90, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 450, sports: ["Basketball", "Hockey", "Soccer", "Crew"], greekLife: false,
    website: "https://www.bu.edu", image: IMG.boston,
    tags: ["Urban", "Research", "Global", "Arts"],
    strongPrograms: ["Communications", "Computer Science", "Film", "Business", "Economics"],
    earlyDecision: "11-01", regularDecision: "01-04",
  },
  {
    name: "Northeastern University", slug: "northeastern-university", shortName: "Northeastern",
    city: "Boston", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 16500,
    acceptanceRate: 7, avgGpa: 3.9, satRange: [1440, 1540], actRange: [33, 35],
    graduationRate: 90, studentFacultyRatio: "14:1",
    tuitionInternational: 60000, roomAndBoard: 19000, estimatedTotalCost: 79000,
    intlAid: false, meritScholarships: true, needBasedAid: false, meetsFullNeed: false, avgAid: 15000,
    intlPercentage: 32, intlPopulation: 5280, toeflMin: 99, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 400, sports: ["Basketball", "Hockey", "Soccer", "Track"], greekLife: true,
    website: "https://www.northeastern.edu", image: IMG.boston,
    tags: ["Co-op", "STEM", "Urban", "Global"],
    strongPrograms: ["Computer Science", "Business", "Engineering", "Health Sciences", "Data Science"],
    earlyAction: "11-01", regularDecision: "01-01",
  },
  {
    name: "University of Notre Dame", slug: "university-of-notre-dame", shortName: "Notre Dame",
    city: "Notre Dame", state: "Indiana", stateCode: "IN", region: "MIDWEST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 8900,
    acceptanceRate: 15, avgGpa: 3.9, satRange: [1410, 1530], actRange: [33, 35],
    graduationRate: 96, studentFacultyRatio: "10:1",
    tuitionInternational: 60000, roomAndBoard: 16000, estimatedTotalCost: 76000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 30000,
    intlPercentage: 10, intlPopulation: 890, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 400, sports: ["Football", "Basketball", "Hockey", "Soccer"], greekLife: false,
    website: "https://www.nd.edu", image: IMG.hero,
    tags: ["Catholic", "Research", "Division I", "Tradition"],
    strongPrograms: ["Business", "Engineering", "Economics", "Political Science", "Psychology"],
    earlyAction: "11-01", regularDecision: "01-01",
  },
  {
    name: "University of Chicago", slug: "university-of-chicago", shortName: "UChicago",
    city: "Chicago", state: "Illinois", stateCode: "IL", region: "MIDWEST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7100,
    acceptanceRate: 5.4, avgGpa: 3.95, satRange: [1510, 1580], actRange: [34, 36],
    graduationRate: 94, studentFacultyRatio: "5:1",
    tuitionInternational: 62000, roomAndBoard: 19000, estimatedTotalCost: 81000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 58000,
    intlPercentage: 18, intlPopulation: 1280, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 400, sports: ["Basketball", "Soccer", "Tennis", "Swimming"], greekLife: true,
    website: "https://www.uchicago.edu", image: IMG.hero,
    tags: ["Research", "Economics", "Core Curriculum", "Global"],
    strongPrograms: ["Economics", "Mathematics", "Philosophy", "Computer Science", "Political Science"],
    earlyAction: "11-01", earlyDecision: "11-01", regularDecision: "01-02",
  },
  {
    name: "Northwestern University", slug: "northwestern-university", shortName: "Northwestern",
    city: "Evanston", state: "Illinois", stateCode: "IL", region: "MIDWEST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 8800,
    acceptanceRate: 7, avgGpa: 3.95, satRange: [1470, 1560], actRange: [33, 35],
    graduationRate: 96, studentFacultyRatio: "6:1",
    tuitionInternational: 63000, roomAndBoard: 19500, estimatedTotalCost: 82500,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 54000,
    intlPercentage: 13, intlPopulation: 1140, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 500, sports: ["Football", "Basketball", "Soccer", "Swimming"], greekLife: true,
    website: "https://www.northwestern.edu", image: IMG.hero,
    tags: ["Research", "Journalism", "Big Ten", "Arts"],
    strongPrograms: ["Journalism", "Economics", "Communications", "Engineering", "Film"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Duke University", slug: "duke-university", shortName: "Duke",
    city: "Durham", state: "North Carolina", stateCode: "NC", region: "EAST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 6900,
    acceptanceRate: 6, avgGpa: 3.95, satRange: [1490, 1570], actRange: [34, 36],
    graduationRate: 96, studentFacultyRatio: "6:1",
    tuitionInternational: 63000, roomAndBoard: 17500, estimatedTotalCost: 80500,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 55000,
    intlPercentage: 13, intlPopulation: 900, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 400, sports: ["Basketball", "Football", "Lacrosse", "Tennis"], greekLife: true,
    website: "https://duke.edu", image: IMG.hero,
    tags: ["Research", "Basketball", "Pre-Medicine", "Engineering"],
    strongPrograms: ["Pre-Medicine", "Economics", "Computer Science", "Public Policy", "Engineering"],
    earlyDecision: "11-01", regularDecision: "01-02",
  },
  {
    name: "Vanderbilt University", slug: "vanderbilt-university", shortName: "Vanderbilt",
    city: "Nashville", state: "Tennessee", stateCode: "TN", region: "SOUTH",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7200,
    acceptanceRate: 6.7, avgGpa: 3.9, satRange: [1490, 1570], actRange: [34, 35],
    graduationRate: 94, studentFacultyRatio: "7:1",
    tuitionInternational: 59000, roomAndBoard: 19000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: true, avgAid: 52000,
    intlPercentage: 10, intlPopulation: 720, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 500, sports: ["Football", "Basketball", "Soccer", "Lacrosse"], greekLife: true,
    website: "https://www.vanderbilt.edu", image: IMG.florida,
    tags: ["Research", "Pre-Medicine", "Southern", "SEC"],
    strongPrograms: ["Pre-Medicine", "Engineering", "Economics", "Computer Science", "Political Science"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Rice University", slug: "rice-university", shortName: "Rice",
    city: "Houston", state: "Texas", stateCode: "TX", region: "SOUTH",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 4700,
    acceptanceRate: 8.7, avgGpa: 3.95, satRange: [1490, 1570], actRange: [34, 35],
    graduationRate: 94, studentFacultyRatio: "6:1",
    tuitionInternational: 54000, roomAndBoard: 16000, estimatedTotalCost: 70000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 47000,
    intlPercentage: 13, intlPopulation: 610, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 200, sports: ["Baseball", "Basketball", "Soccer", "Track"], greekLife: false,
    website: "https://www.rice.edu", image: IMG.hero,
    tags: ["Research", "STEM", "College System", "Engineering"],
    strongPrograms: ["Engineering", "Computer Science", "Economics", "Bioengineering", "Business"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Emory University", slug: "emory-university", shortName: "Emory",
    city: "Atlanta", state: "Georgia", stateCode: "GA", region: "EAST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7200,
    acceptanceRate: 13, avgGpa: 3.9, satRange: [1430, 1540], actRange: [32, 35],
    graduationRate: 91, studentFacultyRatio: "9:1",
    tuitionInternational: 59000, roomAndBoard: 17000, estimatedTotalCost: 76000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 32000,
    intlPercentage: 18, intlPopulation: 1300, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 2 years", clubs: 350, sports: ["Basketball", "Soccer", "Tennis", "Swimming"], greekLife: true,
    website: "https://www.emory.edu", image: IMG.florida,
    tags: ["Research", "Pre-Medicine", "Business", "Public Health"],
    strongPrograms: ["Pre-Medicine", "Business", "Nursing", "Psychology", "Public Health"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "University of Southern California", slug: "university-of-southern-california", shortName: "USC",
    city: "Los Angeles", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 21000,
    acceptanceRate: 12, avgGpa: 3.9, satRange: [1460, 1560], actRange: [33, 35],
    graduationRate: 92, studentFacultyRatio: "9:1",
    tuitionInternational: 66000, roomAndBoard: 18500, estimatedTotalCost: 84500,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 34000,
    intlPercentage: 15, intlPopulation: 3150, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 1000, sports: ["Football", "Basketball", "Volleyball", "Swimming"], greekLife: true,
    website: "https://www.usc.edu", image: IMG.california,
    tags: ["Film", "Engineering", "Business", "Urban"],
    strongPrograms: ["Film", "Computer Science", "Business", "Communications", "Engineering"],
    earlyAction: "11-01", regularDecision: "01-15",
  },
  {
    name: "Stanford University", slug: "stanford-university", shortName: "Stanford",
    city: "Stanford", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7800,
    acceptanceRate: 3.9, avgGpa: 4.0, satRange: [1510, 1580], actRange: [34, 36],
    graduationRate: 96, studentFacultyRatio: "5:1",
    tuitionInternational: 62000, roomAndBoard: 20000, estimatedTotalCost: 82000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 62000,
    intlPercentage: 13, intlPopulation: 1010, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 650, sports: ["Football", "Basketball", "Soccer", "Tennis"], greekLife: false,
    website: "https://www.stanford.edu", image: IMG.california,
    tags: ["Silicon Valley", "Research", "STEM", "Need-Blind"],
    strongPrograms: ["Computer Science", "Engineering", "Economics", "Biology", "Business"],
    earlyAction: "11-01", regularDecision: "01-05",
  },

  // ============================================================
  // PUBLIC UNIVERSITIES
  // ============================================================
  {
    name: "University of Florida", slug: "university-of-florida", shortName: "UF",
    city: "Gainesville", state: "Florida", stateCode: "FL", region: "EAST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 34500,
    acceptanceRate: 24, avgGpa: 4.1, satRange: [1330, 1490], actRange: [30, 34],
    graduationRate: 88, studentFacultyRatio: "17:1",
    tuitionInState: 6400, tuitionOutOfState: 28700, tuitionInternational: 28700, roomAndBoard: 11000, estimatedTotalCost: 39700,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 8, intlPopulation: 2760, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1000, sports: ["Football", "Basketball", "Baseball", "Swimming"], greekLife: true,
    website: "https://www.ufl.edu", image: IMG.florida,
    tags: ["Research University", "SEC", "Division I", "Flagship"], featured: true,
    strongPrograms: ["Engineering", "Business", "Agriculture", "Public Health", "Psychology"],
    regularDecision: "11-01", rolling: true,
  },
  {
    name: "UCLA", slug: "ucla", shortName: "UCLA",
    city: "Los Angeles", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 32300,
    acceptanceRate: 9, avgGpa: 4.2, satRange: [1290, 1530], actRange: [29, 35],
    graduationRate: 91, studentFacultyRatio: "18:1",
    tuitionInState: 13400, tuitionOutOfState: 44900, tuitionInternational: 44900, roomAndBoard: 18100, estimatedTotalCost: 63000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 19, intlPopulation: 6140, toeflMin: 100, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 1000, sports: ["Football", "Basketball", "Soccer", "Volleyball"], greekLife: true,
    website: "https://www.ucla.edu", image: IMG.california,
    tags: ["Research", "Public Ivy", "Division I", "PAC-12"], featured: true,
    strongPrograms: ["Film", "Engineering", "Biology", "Psychology", "Economics"],
    regularDecision: "11-30",
  },
  {
    name: "University of Michigan", slug: "university-of-michigan", shortName: "UMich",
    city: "Ann Arbor", state: "Michigan", stateCode: "MI", region: "MIDWEST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 32000,
    acceptanceRate: 18, avgGpa: 3.9, satRange: [1360, 1540], actRange: [32, 35],
    graduationRate: 93, studentFacultyRatio: "15:1",
    tuitionInState: 17000, tuitionOutOfState: 55000, tuitionInternational: 55000, roomAndBoard: 13000, estimatedTotalCost: 68000,
    intlAid: true, meritScholarships: true, needBasedAid: false,
    intlPercentage: 16, intlPopulation: 5120, toeflMin: 100, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 1600, sports: ["Football", "Basketball", "Swimming", "Hockey"], greekLife: true,
    website: "https://umich.edu", image: IMG.boston,
    tags: ["Research", "Public Ivy", "Big Ten", "Division I"],
    strongPrograms: ["Engineering", "Business", "Computer Science", "Political Science", "Economics"],
    earlyAction: "11-01", regularDecision: "02-01",
  },
  {
    name: "University of California, Berkeley", slug: "university-of-california-berkeley", shortName: "UC Berkeley",
    city: "Berkeley", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 32200,
    acceptanceRate: 12, avgGpa: 4.0, satRange: [1310, 1530], actRange: [30, 35],
    graduationRate: 93, studentFacultyRatio: "19:1",
    tuitionInState: 14400, tuitionOutOfState: 44300, tuitionInternational: 44300, roomAndBoard: 20000, estimatedTotalCost: 64300,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 17, intlPopulation: 5470, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1000, sports: ["Football", "Basketball", "Rugby", "Swimming"], greekLife: true,
    website: "https://www.berkeley.edu", image: IMG.california,
    tags: ["Research", "Public Ivy", "STEM", "Silicon Valley"],
    strongPrograms: ["Computer Science", "Engineering", "Economics", "Mathematics", "Business"],
    regularDecision: "11-30",
  },
  {
    name: "University of California, San Diego", slug: "uc-san-diego", shortName: "UCSD",
    city: "La Jolla", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 33600,
    acceptanceRate: 24, avgGpa: 3.9, satRange: [1270, 1510], actRange: [27, 34],
    graduationRate: 88, studentFacultyRatio: "19:1",
    tuitionInState: 14500, tuitionOutOfState: 46000, tuitionInternational: 46000, roomAndBoard: 16000, estimatedTotalCost: 62000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 20, intlPopulation: 6720, toeflMin: 83, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 500, sports: ["Soccer", "Basketball", "Swimming", "Volleyball"], greekLife: true,
    website: "https://ucsd.edu", image: IMG.california,
    tags: ["Research", "STEM", "Oceanography", "Public Ivy"],
    strongPrograms: ["Computer Science", "Biology", "Engineering", "Data Science", "Psychology"],
    regularDecision: "11-30",
  },
  {
    name: "University of California, Irvine", slug: "uc-irvine", shortName: "UCI",
    city: "Irvine", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 28500,
    acceptanceRate: 21, avgGpa: 3.95, satRange: [1220, 1450], actRange: [25, 33],
    graduationRate: 87, studentFacultyRatio: "18:1",
    tuitionInState: 14500, tuitionOutOfState: 46000, tuitionInternational: 46000, roomAndBoard: 15000, estimatedTotalCost: 61000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 24, intlPopulation: 6840, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 500, sports: ["Soccer", "Basketball", "Baseball", "Tennis"], greekLife: true,
    website: "https://www.uci.edu", image: IMG.california,
    tags: ["Research", "STEM", "Tech", "Diversity"],
    strongPrograms: ["Computer Science", "Engineering", "Business", "Biology", "Data Science"],
    regularDecision: "11-30",
  },
  {
    name: "Georgia Institute of Technology", slug: "georgia-tech", shortName: "Georgia Tech",
    city: "Atlanta", state: "Georgia", stateCode: "GA", region: "EAST_COAST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 18500,
    acceptanceRate: 17, avgGpa: 4.0, satRange: [1370, 1530], actRange: [31, 35],
    graduationRate: 92, studentFacultyRatio: "22:1",
    tuitionInState: 11000, tuitionOutOfState: 33000, tuitionInternational: 33000, roomAndBoard: 15000, estimatedTotalCost: 48000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 10, intlPopulation: 1850, toeflMin: 95, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 350, sports: ["Football", "Basketball", "Baseball", "Track"], greekLife: true,
    website: "https://www.gatech.edu", image: IMG.florida,
    tags: ["STEM", "Engineering", "Research", "Tech"],
    strongPrograms: ["Engineering", "Computer Science", "Aerospace Engineering", "Mechanical Engineering", "Business"],
    earlyAction: "10-15", regularDecision: "01-04",
  },
  {
    name: "University of Virginia", slug: "university-of-virginia", shortName: "UVA",
    city: "Charlottesville", state: "Virginia", stateCode: "VA", region: "EAST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 17400,
    acceptanceRate: 19, avgGpa: 4.0, satRange: [1400, 1520], actRange: [32, 35],
    graduationRate: 94, studentFacultyRatio: "15:1",
    tuitionInState: 19000, tuitionOutOfState: 56000, tuitionInternational: 56000, roomAndBoard: 14000, estimatedTotalCost: 70000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 25000,
    intlPercentage: 8, intlPopulation: 1390, toeflMin: 90, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 800, sports: ["Basketball", "Football", "Soccer", "Lacrosse"], greekLife: true,
    website: "https://www.virginia.edu", image: IMG.hero,
    tags: ["Public Ivy", "Research", "ACC", "Founding Fathers"],
    strongPrograms: ["Business", "Economics", "Political Science", "Engineering", "Psychology"],
    earlyAction: "11-01", regularDecision: "01-15",
  },
  {
    name: "University of North Carolina at Chapel Hill", slug: "university-of-north-carolina-chapel-hill", shortName: "UNC",
    city: "Chapel Hill", state: "North Carolina", stateCode: "NC", region: "EAST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 20400,
    acceptanceRate: 20, avgGpa: 3.9, satRange: [1370, 1510], actRange: [30, 34],
    graduationRate: 90, studentFacultyRatio: "14:1",
    tuitionInState: 9000, tuitionOutOfState: 39000, tuitionInternational: 39000, roomAndBoard: 13000, estimatedTotalCost: 52000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 20000,
    intlPercentage: 6, intlPopulation: 1220, toeflMin: 100, ieltsMin: 7.5,
    housing: "First year guaranteed", clubs: 800, sports: ["Basketball", "Football", "Soccer", "Swimming"], greekLife: true,
    website: "https://www.unc.edu", image: IMG.hero,
    tags: ["Public Ivy", "Research", "ACC", "Flagship"],
    strongPrograms: ["Business", "Computer Science", "Psychology", "Biology", "Communications"],
    earlyAction: "10-15", regularDecision: "01-15",
  },
  {
    name: "University of Texas at Austin", slug: "university-of-texas-austin", shortName: "UT Austin",
    city: "Austin", state: "Texas", stateCode: "TX", region: "SOUTH",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 42000,
    acceptanceRate: 29, avgGpa: 3.85, satRange: [1240, 1480], actRange: [28, 34],
    graduationRate: 86, studentFacultyRatio: "18:1",
    tuitionInState: 11500, tuitionOutOfState: 41000, tuitionInternational: 41000, roomAndBoard: 14000, estimatedTotalCost: 55000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 7, intlPopulation: 2940, toeflMin: 79, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1300, sports: ["Football", "Basketball", "Baseball", "Swimming"], greekLife: true,
    website: "https://www.utexas.edu", image: IMG.hero,
    tags: ["Research", "Big 12", "Flagship", "Tech Hub"],
    strongPrograms: ["Computer Science", "Engineering", "Business", "Architecture", "Economics"],
    regularDecision: "12-01",
  },
  {
    name: "University of Illinois Urbana-Champaign", slug: "university-of-illinois-urbana-champaign", shortName: "UIUC",
    city: "Champaign", state: "Illinois", stateCode: "IL", region: "MIDWEST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 34000,
    acceptanceRate: 45, avgGpa: 3.8, satRange: [1240, 1470], actRange: [26, 33],
    graduationRate: 86, studentFacultyRatio: "20:1",
    tuitionInState: 17000, tuitionOutOfState: 37000, tuitionInternational: 37000, roomAndBoard: 12000, estimatedTotalCost: 49000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 22, intlPopulation: 7480, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1000, sports: ["Football", "Basketball", "Baseball", "Golf"], greekLife: true,
    website: "https://illinois.edu", image: IMG.hero,
    tags: ["STEM", "Engineering", "Big Ten", "Research"],
    strongPrograms: ["Engineering", "Computer Science", "Data Science", "Business", "Architecture"],
    earlyAction: "11-01", regularDecision: "01-05",
  },
  {
    name: "University of Wisconsin-Madison", slug: "university-of-wisconsin-madison", shortName: "Wisconsin",
    city: "Madison", state: "Wisconsin", stateCode: "WI", region: "MIDWEST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 37000,
    acceptanceRate: 49, avgGpa: 3.85, satRange: [1370, 1520], actRange: [29, 34],
    graduationRate: 88, studentFacultyRatio: "17:1",
    tuitionInState: 11000, tuitionOutOfState: 40000, tuitionInternational: 40000, roomAndBoard: 13000, estimatedTotalCost: 53000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 9, intlPopulation: 3330, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 900, sports: ["Football", "Basketball", "Hockey", "Volleyball"], greekLife: true,
    website: "https://www.wisc.edu", image: IMG.hero,
    tags: ["Research", "Big Ten", "Badgers", "Flagship"],
    strongPrograms: ["Engineering", "Computer Science", "Business", "Economics", "Biology"],
    earlyAction: "11-01", regularDecision: "01-15",
  },
  {
    name: "University of Washington", slug: "university-of-washington", shortName: "UW",
    city: "Seattle", state: "Washington", stateCode: "WA", region: "WEST_COAST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 36000,
    acceptanceRate: 53, avgGpa: 3.8, satRange: [1200, 1450], actRange: [24, 32],
    graduationRate: 84, studentFacultyRatio: "19:1",
    tuitionInState: 12000, tuitionOutOfState: 40000, tuitionInternational: 40000, roomAndBoard: 14000, estimatedTotalCost: 54000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 16, intlPopulation: 5760, toeflMin: 92, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 900, sports: ["Football", "Basketball", "Soccer", "Crew"], greekLife: true,
    website: "https://www.washington.edu", image: IMG.california,
    tags: ["Research", "STEM", "Pacific Northwest", "Tech"],
    strongPrograms: ["Computer Science", "Engineering", "Data Science", "Business", "Biology"],
    regularDecision: "11-15",
  },
  {
    name: "Purdue University", slug: "purdue-university", shortName: "Purdue",
    city: "West Lafayette", state: "Indiana", stateCode: "IN", region: "MIDWEST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 39000,
    acceptanceRate: 53, avgGpa: 3.7, satRange: [1210, 1440], actRange: [26, 33],
    graduationRate: 84, studentFacultyRatio: "13:1",
    tuitionInState: 10000, tuitionOutOfState: 32000, tuitionInternational: 32000, roomAndBoard: 10600, estimatedTotalCost: 42600,
    intlAid: true, meritScholarships: true, needBasedAid: false,
    intlPercentage: 22, intlPopulation: 8580, toeflMin: 80, ieltsMin: 6.5,
    housing: "Available all years", clubs: 1000, sports: ["Football", "Basketball", "Swimming", "Golf"], greekLife: true,
    website: "https://www.purdue.edu", image: IMG.florida,
    tags: ["STEM", "Engineering", "Research", "Big Ten"],
    strongPrograms: ["Engineering", "Computer Science", "Agriculture", "Aerospace Engineering", "Business"],
    earlyAction: "11-01", regularDecision: "02-01",
  },
  {
    name: "Penn State University", slug: "penn-state-university", shortName: "Penn State",
    city: "University Park", state: "Pennsylvania", stateCode: "PA", region: "NORTHEAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 41000,
    acceptanceRate: 56, avgGpa: 3.65, satRange: [1180, 1380], actRange: [25, 31],
    graduationRate: 86, studentFacultyRatio: "14:1",
    tuitionInState: 19000, tuitionOutOfState: 37000, tuitionInternational: 37000, roomAndBoard: 12000, estimatedTotalCost: 49000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 12, intlPopulation: 4920, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1000, sports: ["Football", "Basketball", "Wrestling", "Volleyball"], greekLife: true,
    website: "https://www.psu.edu", image: IMG.hero,
    tags: ["Big Ten", "Division I", "Research", "Flagship"],
    strongPrograms: ["Engineering", "Business", "Communications", "Computer Science", "Architecture"],
    regularDecision: "12-01", rolling: true,
  },
  {
    name: "Ohio State University", slug: "ohio-state-university", shortName: "Ohio State",
    city: "Columbus", state: "Ohio", stateCode: "OH", region: "MIDWEST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 47000,
    acceptanceRate: 57, avgGpa: 3.8, satRange: [1240, 1430], actRange: [26, 32],
    graduationRate: 87, studentFacultyRatio: "18:1",
    tuitionInState: 12000, tuitionOutOfState: 36000, tuitionInternational: 36000, roomAndBoard: 14000, estimatedTotalCost: 50000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 8, intlPopulation: 3760, toeflMin: 79, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1400, sports: ["Football", "Basketball", "Baseball", "Volleyball"], greekLife: true,
    website: "https://www.osu.edu", image: IMG.hero,
    tags: ["Big Ten", "Research", "Flagship", "Division I"],
    strongPrograms: ["Engineering", "Business", "Communications", "Nursing", "Computer Science"],
    regularDecision: "11-01", rolling: true,
  },
  {
    name: "Michigan State University", slug: "michigan-state-university", shortName: "MSU",
    city: "East Lansing", state: "Michigan", stateCode: "MI", region: "MIDWEST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 40000,
    acceptanceRate: 88, avgGpa: 3.7, satRange: [1120, 1320], actRange: [23, 29],
    graduationRate: 82, studentFacultyRatio: "16:1",
    tuitionInState: 15000, tuitionOutOfState: 41000, tuitionInternational: 41000, roomAndBoard: 12000, estimatedTotalCost: 53000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 13, intlPopulation: 5200, toeflMin: 79, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 900, sports: ["Football", "Basketball", "Hockey", "Soccer"], greekLife: true,
    website: "https://msu.edu", image: IMG.hero,
    tags: ["Big Ten", "Research", "Division I", "Agriculture"],
    strongPrograms: ["Business", "Communications", "Engineering", "Psychology", "Agriculture"],
    regularDecision: "11-01", rolling: true,
  },
  {
    name: "Texas A&M University", slug: "texas-a-and-m", shortName: "Texas A&M",
    city: "College Station", state: "Texas", stateCode: "TX", region: "SOUTH",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 57000,
    acceptanceRate: 64, avgGpa: 3.7, satRange: [1170, 1390], actRange: [25, 31],
    graduationRate: 84, studentFacultyRatio: "21:1",
    tuitionInState: 12000, tuitionOutOfState: 40000, tuitionInternational: 40000, roomAndBoard: 12000, estimatedTotalCost: 52000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 5, intlPopulation: 2850, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1000, sports: ["Football", "Basketball", "Baseball", "Track"], greekLife: true,
    website: "https://www.tamu.edu", image: IMG.florida,
    tags: ["SEC", "Division I", "Engineering", "Flagship"],
    strongPrograms: ["Engineering", "Agriculture", "Business", "Aerospace Engineering", "Veterinary Medicine"],
    regularDecision: "12-01", rolling: true,
  },
  {
    name: "University of Maryland", slug: "university-of-maryland", shortName: "UMD",
    city: "College Park", state: "Maryland", stateCode: "MD", region: "EAST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 31000,
    acceptanceRate: 45, avgGpa: 3.85, satRange: [1290, 1490], actRange: [28, 33],
    graduationRate: 88, studentFacultyRatio: "17:1",
    tuitionInState: 11000, tuitionOutOfState: 39000, tuitionInternational: 39000, roomAndBoard: 14000, estimatedTotalCost: 53000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 7, intlPopulation: 2170, toeflMin: 95, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 800, sports: ["Football", "Basketball", "Soccer", "Lacrosse"], greekLife: true,
    website: "https://www.umd.edu", image: IMG.hero,
    tags: ["Big Ten", "Research", "Cybersecurity", "STEM"],
    strongPrograms: ["Computer Science", "Engineering", "Business", "Economics", "Journalism"],
    earlyAction: "11-01", regularDecision: "01-20",
  },
  {
    name: "University of Minnesota", slug: "university-of-minnesota", shortName: "Minnesota",
    city: "Minneapolis", state: "Minnesota", stateCode: "MN", region: "MIDWEST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 39500,
    acceptanceRate: 73, avgGpa: 3.7, satRange: [1240, 1440], actRange: [25, 31],
    graduationRate: 84, studentFacultyRatio: "17:1",
    tuitionInState: 16000, tuitionOutOfState: 34000, tuitionInternational: 34000, roomAndBoard: 12000, estimatedTotalCost: 46000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 12, intlPopulation: 4740, toeflMin: 79, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 900, sports: ["Football", "Basketball", "Hockey", "Volleyball"], greekLife: true,
    website: "https://twin-cities.umn.edu", image: IMG.hero,
    tags: ["Big Ten", "Research", "Flagship", "Public Health"],
    strongPrograms: ["Engineering", "Business", "Economics", "Psychology", "Public Health"],
    regularDecision: "01-01", rolling: true,
  },
  {
    name: "Arizona State University", slug: "arizona-state-university", shortName: "ASU",
    city: "Tempe", state: "Arizona", stateCode: "AZ", region: "SOUTHWEST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 65000,
    acceptanceRate: 90, avgGpa: 3.5, satRange: [1120, 1340], actRange: [22, 29],
    graduationRate: 68, studentFacultyRatio: "19:1",
    tuitionInState: 12000, tuitionOutOfState: 32000, tuitionInternational: 32000, roomAndBoard: 14000, estimatedTotalCost: 46000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 13, intlPopulation: 8450, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 1000, sports: ["Football", "Basketball", "Baseball", "Swimming"], greekLife: true,
    website: "https://www.asu.edu", image: IMG.california,
    tags: ["Innovation", "Research", "Big 12", "Large"],
    strongPrograms: ["Business", "Engineering", "Computer Science", "Communications", "Journalism"],
    regularDecision: "01-01", rolling: true,
  },
  {
    name: "Rutgers University", slug: "rutgers-university", shortName: "Rutgers",
    city: "New Brunswick", state: "New Jersey", stateCode: "NJ", region: "NORTHEAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 36000,
    acceptanceRate: 68, avgGpa: 3.6, satRange: [1210, 1420], actRange: [25, 31],
    graduationRate: 83, studentFacultyRatio: "15:1",
    tuitionInState: 16000, tuitionOutOfState: 33000, tuitionInternational: 33000, roomAndBoard: 14000, estimatedTotalCost: 47000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 10, intlPopulation: 3600, toeflMin: 79, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 700, sports: ["Football", "Basketball", "Soccer", "Wrestling"], greekLife: true,
    website: "https://www.rutgers.edu", image: IMG.nyc,
    tags: ["Big Ten", "Research", "Diversity", "Flagship"],
    strongPrograms: ["Computer Science", "Business", "Engineering", "Pharmacy", "Psychology"],
    regularDecision: "12-01",
  },
  {
    name: "Virginia Tech", slug: "virginia-tech", shortName: "Virginia Tech",
    city: "Blacksburg", state: "Virginia", stateCode: "VA", region: "EAST_COAST",
    type: "PUBLIC", setting: "RURAL", sizeCategory: "LARGE", undergradEnrollment: 30000,
    acceptanceRate: 57, avgGpa: 3.9, satRange: [1220, 1420], actRange: [26, 32],
    graduationRate: 87, studentFacultyRatio: "14:1",
    tuitionInState: 14000, tuitionOutOfState: 33000, tuitionInternational: 33000, roomAndBoard: 12000, estimatedTotalCost: 45000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 9, intlPopulation: 2700, toeflMin: 90, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 800, sports: ["Football", "Basketball", "Soccer", "Wrestling"], greekLife: true,
    website: "https://vt.edu", image: IMG.hero,
    tags: ["Engineering", "ACC", "Research", "Rural Campus"],
    strongPrograms: ["Engineering", "Computer Science", "Business", "Architecture", "Agriculture"],
    regularDecision: "01-15",
  },
  {
    name: "University of Colorado Boulder", slug: "university-of-colorado-boulder", shortName: "CU Boulder",
    city: "Boulder", state: "Colorado", stateCode: "CO", region: "SOUTHWEST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 31000,
    acceptanceRate: 80, avgGpa: 3.6, satRange: [1170, 1380], actRange: [24, 31],
    graduationRate: 74, studentFacultyRatio: "18:1",
    tuitionInState: 12000, tuitionOutOfState: 39000, tuitionInternational: 39000, roomAndBoard: 14000, estimatedTotalCost: 53000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 7, intlPopulation: 2170, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 600, sports: ["Football", "Basketball", "Skiing", "Lacrosse"], greekLife: true,
    website: "https://www.colorado.edu", image: IMG.california,
    tags: ["Big 12", "Outdoor", "Aerospace", "Research"],
    strongPrograms: ["Aerospace Engineering", "Business", "Engineering", "Environmental Science", "Computer Science"],
    earlyAction: "11-15", regularDecision: "01-15",
  },
  {
    name: "University of Georgia", slug: "university-of-georgia", shortName: "UGA",
    city: "Athens", state: "Georgia", stateCode: "GA", region: "EAST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 31000,
    acceptanceRate: 43, avgGpa: 3.9, satRange: [1280, 1480], actRange: [28, 33],
    graduationRate: 87, studentFacultyRatio: "17:1",
    tuitionInState: 11000, tuitionOutOfState: 31000, tuitionInternational: 31000, roomAndBoard: 12000, estimatedTotalCost: 43000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 5, intlPopulation: 1550, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 800, sports: ["Football", "Basketball", "Baseball", "Gymnastics"], greekLife: true,
    website: "https://www.uga.edu", image: IMG.florida,
    tags: ["SEC", "Division I", "Research", "Flagship"],
    strongPrograms: ["Business", "Journalism", "Biology", "Psychology", "Communications"],
    earlyAction: "10-15", regularDecision: "01-01",
  },
  {
    name: "University of Arizona", slug: "university-of-arizona", shortName: "Arizona",
    city: "Tucson", state: "Arizona", stateCode: "AZ", region: "SOUTHWEST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 38000,
    acceptanceRate: 87, avgGpa: 3.6, satRange: [1140, 1360], actRange: [21, 29],
    graduationRate: 66, studentFacultyRatio: "18:1",
    tuitionInState: 12000, tuitionOutOfState: 37000, tuitionInternational: 37000, roomAndBoard: 13000, estimatedTotalCost: 50000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 10, intlPopulation: 3800, toeflMin: 70, ieltsMin: 6.0,
    housing: "First year guaranteed", clubs: 600, sports: ["Football", "Basketball", "Baseball", "Softball"], greekLife: true,
    website: "https://www.arizona.edu", image: IMG.california,
    tags: ["Big 12", "Research", "Space Science", "Flagship"],
    strongPrograms: ["Business", "Engineering", "Computer Science", "Astronomy", "Agriculture"],
    regularDecision: "05-01", rolling: true,
  },
  {
    name: "San Diego State University", slug: "san-diego-state-university", shortName: "SDSU",
    city: "San Diego", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 31000,
    acceptanceRate: 39, avgGpa: 3.7, satRange: [1090, 1320], actRange: [22, 28],
    graduationRate: 77, studentFacultyRatio: "26:1",
    tuitionInState: 8000, tuitionOutOfState: 20000, tuitionInternational: 20000, roomAndBoard: 16000, estimatedTotalCost: 36000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 9, intlPopulation: 2790, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 400, sports: ["Football", "Basketball", "Baseball", "Soccer"], greekLife: true,
    website: "https://www.sdsu.edu", image: IMG.california,
    tags: ["Beach", "Mountain West", "Business", "Public"],
    strongPrograms: ["Business", "Engineering", "Communications", "Psychology", "Biology"],
    regularDecision: "12-01",
  },
  {
    name: "University of Alabama", slug: "university-of-alabama", shortName: "Alabama",
    city: "Tuscaloosa", state: "Alabama", stateCode: "AL", region: "SOUTH",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 31000,
    acceptanceRate: 79, avgGpa: 3.7, satRange: [1100, 1340], actRange: [22, 29],
    graduationRate: 73, studentFacultyRatio: "21:1",
    tuitionInState: 11000, tuitionOutOfState: 33000, tuitionInternational: 33000, roomAndBoard: 14000, estimatedTotalCost: 47000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 5, intlPopulation: 1550, toeflMin: 79, ieltsMin: 6.0,
    housing: "First year guaranteed", clubs: 600, sports: ["Football", "Basketball", "Baseball", "Gymnastics"], greekLife: true,
    website: "https://www.ua.edu", image: IMG.florida,
    tags: ["SEC", "Division I", "Scholarships", "Flagship"],
    strongPrograms: ["Business", "Engineering", "Nursing", "Communications", "Psychology"],
    regularDecision: "05-01", rolling: true,
  },
  {
    name: "Louisiana State University", slug: "louisiana-state-university", shortName: "LSU",
    city: "Baton Rouge", state: "Louisiana", stateCode: "LA", region: "SOUTH",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 30000,
    acceptanceRate: 75, avgGpa: 3.5, satRange: [1080, 1320], actRange: [22, 29],
    graduationRate: 70, studentFacultyRatio: "21:1",
    tuitionInState: 12000, tuitionOutOfState: 28000, tuitionInternational: 28000, roomAndBoard: 14000, estimatedTotalCost: 42000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 6, intlPopulation: 1800, toeflMin: 79, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 400, sports: ["Football", "Basketball", "Baseball", "Gymnastics"], greekLife: true,
    website: "https://www.lsu.edu", image: IMG.florida,
    tags: ["SEC", "Division I", "Flagship", "Agriculture"],
    strongPrograms: ["Business", "Engineering", "Communications", "Agriculture", "Biology"],
    regularDecision: "04-15", rolling: true,
  },
  {
    name: "Iowa State University", slug: "iowa-state-university", shortName: "Iowa State",
    city: "Ames", state: "Iowa", stateCode: "IA", region: "MIDWEST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 25000,
    acceptanceRate: 90, avgGpa: 3.6, satRange: [1090, 1340], actRange: [22, 29],
    graduationRate: 73, studentFacultyRatio: "18:1",
    tuitionInState: 9500, tuitionOutOfState: 26000, tuitionInternational: 26000, roomAndBoard: 10000, estimatedTotalCost: 36000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 12, intlPopulation: 3000, toeflMin: 71, ieltsMin: 6.0,
    housing: "First year guaranteed", clubs: 800, sports: ["Football", "Basketball", "Wrestling", "Volleyball"], greekLife: true,
    website: "https://www.iastate.edu", image: IMG.hero,
    tags: ["Big 12", "Engineering", "Agriculture", "Research"],
    strongPrograms: ["Engineering", "Agriculture", "Computer Science", "Business", "Design"],
    regularDecision: "07-01", rolling: true,
  },
  {
    name: "University of Oregon", slug: "university-of-oregon", shortName: "Oregon",
    city: "Eugene", state: "Oregon", stateCode: "OR", region: "WEST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 19000,
    acceptanceRate: 85, avgGpa: 3.6, satRange: [1100, 1320], actRange: [22, 29],
    graduationRate: 73, studentFacultyRatio: "17:1",
    tuitionInState: 13000, tuitionOutOfState: 39000, tuitionInternational: 39000, roomAndBoard: 13000, estimatedTotalCost: 52000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 9, intlPopulation: 1710, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 400, sports: ["Football", "Basketball", "Track", "Soccer"], greekLife: true,
    website: "https://www.uoregon.edu", image: IMG.california,
    tags: ["Big Ten", "Outdoor", "Design", "Research"],
    strongPrograms: ["Business", "Architecture", "Journalism", "Psychology", "Computer Science"],
    regularDecision: "01-15", rolling: true,
  },
  {
    name: "Temple University", slug: "temple-university", shortName: "Temple",
    city: "Philadelphia", state: "Pennsylvania", stateCode: "PA", region: "NORTHEAST",
    type: "PUBLIC", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 26000,
    acceptanceRate: 80, avgGpa: 3.4, satRange: [1070, 1290], actRange: [22, 28],
    graduationRate: 68, studentFacultyRatio: "13:1",
    tuitionInState: 18000, tuitionOutOfState: 33000, tuitionInternational: 33000, roomAndBoard: 14000, estimatedTotalCost: 47000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 11, intlPopulation: 2860, toeflMin: 79, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 400, sports: ["Basketball", "Football", "Soccer", "Tennis"], greekLife: true,
    website: "https://www.temple.edu", image: IMG.nyc,
    tags: ["Urban", "AAU", "Research", "Diversity"],
    strongPrograms: ["Business", "Communications", "Film", "Engineering", "Music"],
    regularDecision: "02-01", rolling: true,
  },

  // ============================================================
  // SMALL COLLEGES & LIBERAL ARTS
  // ============================================================
  {
    name: "Amherst College", slug: "amherst-college", shortName: "Amherst",
    city: "Amherst", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 1900,
    acceptanceRate: 9, avgGpa: 3.9, satRange: [1430, 1540], actRange: [33, 35],
    graduationRate: 96, studentFacultyRatio: "7:1",
    tuitionInternational: 64000, roomAndBoard: 17000, estimatedTotalCost: 81000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 62000,
    intlPercentage: 11, intlPopulation: 210, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Soccer", "Basketball", "Tennis", "Track"], greekLife: false,
    website: "https://www.amherst.edu", image: IMG.boston,
    tags: ["Liberal Arts", "Need-Blind", "Five College", "Selective"],
    strongPrograms: ["Economics", "Computer Science", "Psychology", "English Literature", "Mathematics"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Williams College", slug: "williams-college", shortName: "Williams",
    city: "Williamstown", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "RURAL", sizeCategory: "SMALL", undergradEnrollment: 2100,
    acceptanceRate: 9, avgGpa: 3.95, satRange: [1450, 1560], actRange: [33, 35],
    graduationRate: 94, studentFacultyRatio: "7:1",
    tuitionInternational: 63000, roomAndBoard: 16000, estimatedTotalCost: 79000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 61000,
    intlPercentage: 12, intlPopulation: 250, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Soccer", "Swimming", "Tennis", "Track"], greekLife: false,
    website: "https://www.williams.edu", image: IMG.hero,
    tags: ["Liberal Arts", "Need-Blind", "Winter Study", "Outdoor"],
    strongPrograms: ["Economics", "Psychology", "Mathematics", "Art History", "History"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Wesleyan University", slug: "wesleyan-university", shortName: "Wesleyan",
    city: "Middletown", state: "Connecticut", stateCode: "CT", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 3000,
    acceptanceRate: 14, avgGpa: 3.85, satRange: [1350, 1510], actRange: [31, 35],
    graduationRate: 91, studentFacultyRatio: "8:1",
    tuitionInternational: 62000, roomAndBoard: 18000, estimatedTotalCost: 80000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 54000,
    intlPercentage: 13, intlPopulation: 390, toeflMin: 100, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 200, sports: ["Soccer", "Basketball", "Lacrosse", "Squash"], greekLife: false,
    website: "https://www.wesleyan.edu", image: IMG.hero,
    tags: ["Liberal Arts", "Arts", "Open Curriculum", "NESCAC"],
    strongPrograms: ["Film", "Economics", "Psychology", "Neuroscience", "Computer Science"],
    earlyDecision: "11-15", regularDecision: "01-01",
  },
  {
    name: "Oberlin College", slug: "oberlin-college", shortName: "Oberlin",
    city: "Oberlin", state: "Ohio", stateCode: "OH", region: "MIDWEST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 2900,
    acceptanceRate: 35, avgGpa: 3.8, satRange: [1320, 1480], actRange: [30, 34],
    graduationRate: 85, studentFacultyRatio: "10:1",
    tuitionInternational: 60000, roomAndBoard: 17000, estimatedTotalCost: 77000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 50000,
    intlPercentage: 14, intlPopulation: 400, toeflMin: 100, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 150, sports: ["Soccer", "Basketball", "Tennis", "Cross Country"], greekLife: false,
    website: "https://www.oberlin.edu", image: IMG.hero,
    tags: ["Liberal Arts", "Music", "Progressivism", "Arts"],
    strongPrograms: ["Music", "Psychology", "Biology", "Environmental Science", "Politics"],
    earlyDecision: "11-15", regularDecision: "01-15",
  },
  {
    name: "Macalester College", slug: "macalester-college", shortName: "Macalester",
    city: "St. Paul", state: "Minnesota", stateCode: "MN", region: "MIDWEST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "SMALL", undergradEnrollment: 2200,
    acceptanceRate: 28, avgGpa: 3.85, satRange: [1330, 1480], actRange: [30, 34],
    graduationRate: 90, studentFacultyRatio: "10:1",
    tuitionInternational: 58000, roomAndBoard: 13000, estimatedTotalCost: 71000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: true, avgAid: 47000,
    intlPercentage: 15, intlPopulation: 330, toeflMin: 100, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Soccer", "Basketball", "Track", "Tennis"], greekLife: false,
    website: "https://www.macalester.edu", image: IMG.hero,
    tags: ["Liberal Arts", "International", "Urban", "Global Studies"],
    strongPrograms: ["International Relations", "Economics", "Political Science", "Computer Science", "Geography"],
    earlyDecision: "11-15", regularDecision: "01-15",
  },
  {
    name: "Bates College", slug: "bates-college", shortName: "Bates",
    city: "Lewiston", state: "Maine", stateCode: "ME", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 1800,
    acceptanceRate: 12, avgGpa: 3.9, satRange: [1380, 1490], actRange: [32, 35],
    graduationRate: 94, studentFacultyRatio: "10:1",
    tuitionInternational: 60000, roomAndBoard: 16000, estimatedTotalCost: 76000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 57000,
    intlPercentage: 10, intlPopulation: 180, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Soccer", "Swimming", "Squash", "Track"], greekLife: false,
    website: "https://www.bates.edu", image: IMG.hero,
    tags: ["Liberal Arts", "NESCAC", "Outdoor", "Short Term"],
    strongPrograms: ["Political Science", "Economics", "Psychology", "Biology", "Environmental Science"],
    earlyDecision: "11-15", regularDecision: "01-01",
  },
  {
    name: "Colby College", slug: "colby-college", shortName: "Colby",
    city: "Waterville", state: "Maine", stateCode: "ME", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 2000,
    acceptanceRate: 12, avgGpa: 3.9, satRange: [1380, 1510], actRange: [32, 35],
    graduationRate: 94, studentFacultyRatio: "10:1",
    tuitionInternational: 61000, roomAndBoard: 16000, estimatedTotalCost: 77000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 58000,
    intlPercentage: 12, intlPopulation: 240, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Swimming", "Soccer", "Skiing", "Track"], greekLife: false,
    website: "https://www.colby.edu", image: IMG.hero,
    tags: ["Liberal Arts", "Environmental", "NESCAC", "4-1-4"],
    strongPrograms: ["Environmental Science", "Economics", "Government", "Computer Science", "Biology"],
    earlyDecision: "11-15", regularDecision: "01-01",
  },
  {
    name: "Middlebury College", slug: "middlebury-college", shortName: "Middlebury",
    city: "Middlebury", state: "Vermont", stateCode: "VT", region: "NORTHEAST",
    type: "PRIVATE", setting: "RURAL", sizeCategory: "SMALL", undergradEnrollment: 2600,
    acceptanceRate: 13, avgGpa: 3.9, satRange: [1390, 1520], actRange: [32, 35],
    graduationRate: 95, studentFacultyRatio: "8:1",
    tuitionInternational: 62000, roomAndBoard: 17000, estimatedTotalCost: 79000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 56000,
    intlPercentage: 11, intlPopulation: 290, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 150, sports: ["Skiing", "Soccer", "Lacrosse", "Hockey"], greekLife: false,
    website: "https://www.middlebury.edu", image: IMG.hero,
    tags: ["Liberal Arts", "Languages", "Outdoor", "NESCAC"],
    strongPrograms: ["International Relations", "Environmental Science", "Economics", "Political Science", "Spanish"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Pomona College", slug: "pomona-college", shortName: "Pomona",
    city: "Claremont", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 1700,
    acceptanceRate: 7, avgGpa: 4.0, satRange: [1410, 1550], actRange: [31, 35],
    graduationRate: 96, studentFacultyRatio: "8:1",
    tuitionInternational: 58000, roomAndBoard: 18000, estimatedTotalCost: 76000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 59000,
    intlPercentage: 12, intlPopulation: 200, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 150, sports: ["Soccer", "Basketball", "Tennis", "Track"], greekLife: false,
    website: "https://www.pomona.edu", image: IMG.california,
    tags: ["Liberal Arts", "Claremont Consortium", "Need-Blind", "STEM"],
    strongPrograms: ["Computer Science", "Economics", "Mathematics", "Neuroscience", "Politics"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },
  {
    name: "Smith College", slug: "smith-college", shortName: "Smith",
    city: "Northampton", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "SMALL", undergradEnrollment: 2600,
    acceptanceRate: 25, avgGpa: 3.85, satRange: [1290, 1470], actRange: [29, 33],
    graduationRate: 89, studentFacultyRatio: "9:1",
    tuitionInternational: 60000, roomAndBoard: 18000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 53000,
    intlPercentage: 17, intlPopulation: 440, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 130, sports: ["Soccer", "Basketball", "Swimming", "Rowing"], greekLife: false,
    website: "https://www.smith.edu", image: IMG.boston,
    tags: ["Liberal Arts", "Women's College", "Five College", "Arts"],
    strongPrograms: ["Engineering", "Film", "Economics", "Psychology", "Art History"],
    earlyDecision: "11-15", regularDecision: "01-15",
  },
  {
    name: "Carleton College", slug: "carleton-college", shortName: "Carleton",
    city: "Northfield", state: "Minnesota", stateCode: "MN", region: "MIDWEST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 2000,
    acceptanceRate: 17, avgGpa: 3.9, satRange: [1370, 1510], actRange: [31, 34],
    graduationRate: 94, studentFacultyRatio: "8:1",
    tuitionInternational: 62000, roomAndBoard: 14000, estimatedTotalCost: 76000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 54000,
    intlPercentage: 10, intlPopulation: 200, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Soccer", "Basketball", "Swimming", "Ultimate"], greekLife: false,
    website: "https://www.carleton.edu", image: IMG.hero,
    tags: ["Liberal Arts", "STEM", "Three-Term", "Midwest"],
    strongPrograms: ["Computer Science", "Economics", "Biology", "Mathematics", "Physics"],
    earlyDecision: "11-15", regularDecision: "01-15",
  },
  {
    name: "Grinnell College", slug: "grinnell-college", shortName: "Grinnell",
    city: "Grinnell", state: "Iowa", stateCode: "IA", region: "MIDWEST",
    type: "PRIVATE", setting: "RURAL", sizeCategory: "SMALL", undergradEnrollment: 1700,
    acceptanceRate: 11, avgGpa: 3.9, satRange: [1380, 1530], actRange: [30, 34],
    graduationRate: 88, studentFacultyRatio: "8:1",
    tuitionInternational: 61000, roomAndBoard: 14000, estimatedTotalCost: 75000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 55000,
    intlPercentage: 20, intlPopulation: 340, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Soccer", "Basketball", "Swimming", "Cross Country"], greekLife: false,
    website: "https://www.grinnell.edu", image: IMG.hero,
    tags: ["Liberal Arts", "Open Curriculum", "International", "Social Justice"],
    strongPrograms: ["Economics", "Political Science", "Biology", "Computer Science", "History"],
    earlyDecision: "11-15", regularDecision: "01-15",
  },
  {
    name: "Scripps College", slug: "scripps-college", shortName: "Scripps",
    city: "Claremont", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 1100,
    acceptanceRate: 28, avgGpa: 3.9, satRange: [1360, 1510], actRange: [30, 34],
    graduationRate: 92, studentFacultyRatio: "10:1",
    tuitionInternational: 60000, roomAndBoard: 18000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: true, avgAid: 52000,
    intlPercentage: 9, intlPopulation: 100, toeflMin: 100, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 60, sports: ["Soccer", "Basketball", "Tennis", "Water Polo"], greekLife: false,
    website: "https://www.scrippscollege.edu", image: IMG.california,
    tags: ["Liberal Arts", "Women's College", "Claremont Consortium", "Design"],
    strongPrograms: ["Art History", "Fine Arts", "Psychology", "Economics", "Political Science"],
    earlyDecision: "11-15", regularDecision: "01-05",
  },
  {
    name: "Bryn Mawr College", slug: "bryn-mawr-college", shortName: "Bryn Mawr",
    city: "Bryn Mawr", state: "Pennsylvania", stateCode: "PA", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 1400,
    acceptanceRate: 31, avgGpa: 3.85, satRange: [1310, 1490], actRange: [30, 34],
    graduationRate: 90, studentFacultyRatio: "8:1",
    tuitionInternational: 59000, roomAndBoard: 18000, estimatedTotalCost: 77000,
    intlAid: true, meritScholarships: false, needBasedAid: true, meetsFullNeed: true, avgAid: 51000,
    intlPercentage: 20, intlPopulation: 280, toeflMin: 100, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 100, sports: ["Soccer", "Basketball", "Swimming", "Lacrosse"], greekLife: false,
    website: "https://www.brynmawr.edu", image: IMG.hero,
    tags: ["Liberal Arts", "Women's College", "Seven Sisters", "Research"],
    strongPrograms: ["International Relations", "Mathematics", "Political Science", "Biology", "History"],
    earlyDecision: "11-15", regularDecision: "01-15",
  },
  {
    name: "Olin College of Engineering", slug: "olin-college-of-engineering", shortName: "Olin",
    city: "Needham", state: "Massachusetts", stateCode: "MA", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "SMALL", undergradEnrollment: 350,
    acceptanceRate: 15, avgGpa: 3.95, satRange: [1460, 1560], actRange: [33, 36],
    graduationRate: 97, studentFacultyRatio: "8:1",
    tuitionInternational: 55000, roomAndBoard: 18000, estimatedTotalCost: 73000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: true, avgAid: 45000,
    intlPercentage: 12, intlPopulation: 42, toeflMin: 100, ieltsMin: 7.5,
    housing: "Guaranteed 4 years", clubs: 40, sports: ["Soccer", "Basketball", "Ultimate", "Rock Climbing"], greekLife: false,
    website: "https://www.olin.edu", image: IMG.boston,
    tags: ["Engineering", "Project-Based", "STEM", "Innovation"],
    strongPrograms: ["Mechanical Engineering", "Electrical Engineering", "Computer Science", "Engineering", "Mathematics"],
    earlyDecision: "11-01", regularDecision: "01-01",
  },

  // ============================================================
  // MEDIUM PRIVATE UNIVERSITIES (regional)
  // ============================================================
  {
    name: "University of Denver", slug: "university-of-denver", shortName: "Denver",
    city: "Denver", state: "Colorado", stateCode: "CO", region: "SOUTHWEST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 6100,
    acceptanceRate: 79, avgGpa: 3.6, satRange: [1150, 1350], actRange: [24, 30],
    graduationRate: 77, studentFacultyRatio: "10:1",
    tuitionInternational: 57000, roomAndBoard: 16000, estimatedTotalCost: 73000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 28000,
    intlPercentage: 8, intlPopulation: 490, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 200, sports: ["Hockey", "Soccer", "Basketball", "Lacrosse"], greekLife: true,
    website: "https://www.du.edu", image: IMG.california,
    tags: ["Mountain", "Urban", "Research", "D-I Hockey"],
    strongPrograms: ["Business", "Communications", "Psychology", "Computer Science", "Environmental Science"],
    regularDecision: "01-15",
  },
  {
    name: "Santa Clara University", slug: "santa-clara-university", shortName: "SCU",
    city: "Santa Clara", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 6100,
    acceptanceRate: 49, avgGpa: 3.75, satRange: [1290, 1470], actRange: [29, 33],
    graduationRate: 90, studentFacultyRatio: "10:1",
    tuitionInternational: 60000, roomAndBoard: 18000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 26000,
    intlPercentage: 12, intlPopulation: 730, toeflMin: 90, ieltsMin: 7.0,
    housing: "Guaranteed 4 years", clubs: 150, sports: ["Basketball", "Soccer", "Tennis", "Volleyball"], greekLife: false,
    website: "https://www.scu.edu", image: IMG.california,
    tags: ["Jesuit", "Silicon Valley", "Business", "Engineering"],
    strongPrograms: ["Business", "Computer Science", "Engineering", "Economics", "Psychology"],
    regularDecision: "01-07",
  },
  {
    name: "Fordham University", slug: "fordham-university", shortName: "Fordham",
    city: "New York", state: "New York", stateCode: "NY", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 9800,
    acceptanceRate: 58, avgGpa: 3.7, satRange: [1270, 1430], actRange: [28, 32],
    graduationRate: 84, studentFacultyRatio: "14:1",
    tuitionInternational: 58000, roomAndBoard: 19000, estimatedTotalCost: 77000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 27000,
    intlPercentage: 14, intlPopulation: 1370, toeflMin: 90, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 200, sports: ["Basketball", "Soccer", "Football", "Crew"], greekLife: false,
    website: "https://www.fordham.edu", image: IMG.nyc,
    tags: ["Jesuit", "Urban", "New York", "Liberal Arts"],
    strongPrograms: ["Business", "Communications", "Theater", "Psychology", "Political Science"],
    regularDecision: "02-01", rolling: true,
  },
  {
    name: "Chapman University", slug: "chapman-university", shortName: "Chapman",
    city: "Orange", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7800,
    acceptanceRate: 73, avgGpa: 3.7, satRange: [1220, 1400], actRange: [25, 31],
    graduationRate: 83, studentFacultyRatio: "12:1",
    tuitionInternational: 60000, roomAndBoard: 18000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 24000,
    intlPercentage: 7, intlPopulation: 550, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 200, sports: ["Baseball", "Basketball", "Soccer", "Tennis"], greekLife: true,
    website: "https://www.chapman.edu", image: IMG.california,
    tags: ["Film", "Business", "California", "Creative"],
    strongPrograms: ["Film", "Business", "Communications", "Psychology", "Political Science"],
    regularDecision: "01-15",
  },
  {
    name: "Baylor University", slug: "baylor-university", shortName: "Baylor",
    city: "Waco", state: "Texas", stateCode: "TX", region: "SOUTH",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 15000,
    acceptanceRate: 57, avgGpa: 3.7, satRange: [1230, 1390], actRange: [25, 31],
    graduationRate: 79, studentFacultyRatio: "15:1",
    tuitionInternational: 52000, roomAndBoard: 14000, estimatedTotalCost: 66000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 23000,
    intlPercentage: 7, intlPopulation: 1050, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 400, sports: ["Football", "Basketball", "Baseball", "Tennis"], greekLife: true,
    website: "https://www.baylor.edu", image: IMG.florida,
    tags: ["Baptist", "Big 12", "Research", "Southern"],
    strongPrograms: ["Business", "Pre-Medicine", "Communications", "Nursing", "Biology"],
    earlyAction: "11-01", regularDecision: "02-01",
  },
  {
    name: "Pepperdine University", slug: "pepperdine-university", shortName: "Pepperdine",
    city: "Malibu", state: "California", stateCode: "CA", region: "WEST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 3700,
    acceptanceRate: 49, avgGpa: 3.75, satRange: [1260, 1430], actRange: [26, 31],
    graduationRate: 84, studentFacultyRatio: "13:1",
    tuitionInternational: 61000, roomAndBoard: 17000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 27000,
    intlPercentage: 11, intlPopulation: 410, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 80, sports: ["Volleyball", "Basketball", "Tennis", "Swimming"], greekLife: false,
    website: "https://www.pepperdine.edu", image: IMG.california,
    tags: ["Ocean View", "Malibu", "Christian", "Study Abroad"],
    strongPrograms: ["Business", "Communications", "Film", "Psychology", "Political Science"],
    regularDecision: "01-05",
  },
  {
    name: "Villanova University", slug: "villanova-university", shortName: "Villanova",
    city: "Villanova", state: "Pennsylvania", stateCode: "PA", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 7000,
    acceptanceRate: 25, avgGpa: 3.9, satRange: [1380, 1490], actRange: [31, 34],
    graduationRate: 91, studentFacultyRatio: "11:1",
    tuitionInternational: 62000, roomAndBoard: 16000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 28000,
    intlPercentage: 6, intlPopulation: 420, toeflMin: 90, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 300, sports: ["Basketball", "Football", "Lacrosse", "Soccer"], greekLife: true,
    website: "https://www.villanova.edu", image: IMG.hero,
    tags: ["Augustinian", "Business", "Big East", "Basketball"],
    strongPrograms: ["Business", "Nursing", "Engineering", "Communications", "Economics"],
    earlyAction: "11-01", regularDecision: "01-15",
  },
  {
    name: "University of Miami", slug: "university-of-miami", shortName: "Miami",
    city: "Coral Gables", state: "Florida", stateCode: "FL", region: "EAST_COAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 12000,
    acceptanceRate: 19, avgGpa: 3.8, satRange: [1280, 1450], actRange: [28, 33],
    graduationRate: 84, studentFacultyRatio: "12:1",
    tuitionInternational: 59000, roomAndBoard: 17000, estimatedTotalCost: 76000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 29000,
    intlPercentage: 17, intlPopulation: 2040, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 300, sports: ["Football", "Basketball", "Baseball", "Tennis"], greekLife: true,
    website: "https://www.miami.edu", image: IMG.florida,
    tags: ["Tropical", "ACC", "Marine Science", "Research"],
    strongPrograms: ["Business", "Marine Science", "Communications", "Pre-Medicine", "Architecture"],
    earlyAction: "11-01", regularDecision: "01-01",
  },
  {
    name: "George Washington University", slug: "george-washington-university", shortName: "GWU",
    city: "Washington", state: "District of Columbia", stateCode: "DC", region: "EAST_COAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 11300,
    acceptanceRate: 49, avgGpa: 3.8, satRange: [1280, 1440], actRange: [28, 32],
    graduationRate: 85, studentFacultyRatio: "12:1",
    tuitionInternational: 61000, roomAndBoard: 16000, estimatedTotalCost: 77000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 28000,
    intlPercentage: 15, intlPopulation: 1700, toeflMin: 90, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 500, sports: ["Basketball", "Soccer", "Volleyball", "Crew"], greekLife: true,
    website: "https://www.gwu.edu", image: IMG.nyc,
    tags: ["Policy", "Urban", "International Relations", "DC"],
    strongPrograms: ["International Relations", "Political Science", "Business", "Economics", "Communications"],
    earlyDecision: "11-01", regularDecision: "01-05",
  },
  {
    name: "Syracuse University", slug: "syracuse-university", shortName: "Syracuse",
    city: "Syracuse", state: "New York", stateCode: "NY", region: "NORTHEAST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "LARGE", undergradEnrollment: 15000,
    acceptanceRate: 59, avgGpa: 3.6, satRange: [1210, 1370], actRange: [26, 31],
    graduationRate: 83, studentFacultyRatio: "15:1",
    tuitionInternational: 60000, roomAndBoard: 17000, estimatedTotalCost: 77000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 24000,
    intlPercentage: 20, intlPopulation: 3000, toeflMin: 85, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 300, sports: ["Basketball", "Football", "Lacrosse", "Soccer"], greekLife: true,
    website: "https://www.syracuse.edu", image: IMG.nyc,
    tags: ["ACC", "Communications", "Film", "Architecture"],
    strongPrograms: ["Communications", "Film", "Architecture", "Business", "Engineering"],
    earlyAction: "11-15", regularDecision: "01-15",
  },
  {
    name: "University of Rochester", slug: "university-of-rochester", shortName: "Rochester",
    city: "Rochester", state: "New York", stateCode: "NY", region: "NORTHEAST",
    type: "PRIVATE", setting: "SUBURBAN", sizeCategory: "MEDIUM", undergradEnrollment: 6800,
    acceptanceRate: 39, avgGpa: 3.8, satRange: [1350, 1500], actRange: [31, 34],
    graduationRate: 89, studentFacultyRatio: "10:1",
    tuitionInternational: 60000, roomAndBoard: 17000, estimatedTotalCost: 77000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: true, avgAid: 38000,
    intlPercentage: 19, intlPopulation: 1290, toeflMin: 100, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 250, sports: ["Basketball", "Soccer", "Tennis", "Swimming"], greekLife: true,
    website: "https://www.rochester.edu", image: IMG.hero,
    tags: ["Research", "Music", "Open Curriculum", "STEM"],
    strongPrograms: ["Music", "Computer Science", "Optics", "Pre-Medicine", "Economics"],
    earlyDecision: "11-01", regularDecision: "01-05",
  },
  {
    name: "Case Western Reserve University", slug: "case-western-reserve", shortName: "Case Western",
    city: "Cleveland", state: "Ohio", stateCode: "OH", region: "MIDWEST",
    type: "PRIVATE", setting: "URBAN", sizeCategory: "MEDIUM", undergradEnrollment: 5800,
    acceptanceRate: 27, avgGpa: 3.85, satRange: [1390, 1510], actRange: [31, 35],
    graduationRate: 89, studentFacultyRatio: "9:1",
    tuitionInternational: 61000, roomAndBoard: 17000, estimatedTotalCost: 78000,
    intlAid: true, meritScholarships: true, needBasedAid: true, meetsFullNeed: false, avgAid: 36000,
    intlPercentage: 18, intlPopulation: 1040, toeflMin: 90, ieltsMin: 7.0,
    housing: "First year guaranteed", clubs: 200, sports: ["Basketball", "Soccer", "Swimming", "Tennis"], greekLife: true,
    website: "https://case.edu", image: IMG.hero,
    tags: ["Research", "Medical", "STEM", "Engineering"],
    strongPrograms: ["Engineering", "Pre-Medicine", "Computer Science", "Biology", "Data Science"],
    earlyAction: "11-01", regularDecision: "01-15",
  },
  {
    name: "Stony Brook University", slug: "stony-brook-university", shortName: "Stony Brook",
    city: "Stony Brook", state: "New York", stateCode: "NY", region: "NORTHEAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 18000,
    acceptanceRate: 49, avgGpa: 3.6, satRange: [1190, 1400], actRange: [25, 31],
    graduationRate: 73, studentFacultyRatio: "16:1",
    tuitionInState: 10000, tuitionOutOfState: 28000, tuitionInternational: 28000, roomAndBoard: 15000, estimatedTotalCost: 43000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 19, intlPopulation: 3420, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 300, sports: ["Basketball", "Baseball", "Soccer", "Tennis"], greekLife: true,
    website: "https://www.stonybrook.edu", image: IMG.nyc,
    tags: ["SUNY", "Research", "STEM", "Flagship"],
    strongPrograms: ["Computer Science", "Engineering", "Mathematics", "Biology", "Health Sciences"],
    regularDecision: "01-15", rolling: true,
  },
  {
    name: "University of Delaware", slug: "university-of-delaware", shortName: "Delaware",
    city: "Newark", state: "Delaware", stateCode: "DE", region: "EAST_COAST",
    type: "PUBLIC", setting: "SUBURBAN", sizeCategory: "LARGE", undergradEnrollment: 18000,
    acceptanceRate: 72, avgGpa: 3.6, satRange: [1150, 1340], actRange: [24, 30],
    graduationRate: 82, studentFacultyRatio: "13:1",
    tuitionInState: 14000, tuitionOutOfState: 36000, tuitionInternational: 36000, roomAndBoard: 14000, estimatedTotalCost: 50000,
    intlAid: false, meritScholarships: true, needBasedAid: false,
    intlPercentage: 8, intlPopulation: 1440, toeflMin: 80, ieltsMin: 6.5,
    housing: "First year guaranteed", clubs: 300, sports: ["Football", "Basketball", "Lacrosse", "Soccer"], greekLife: true,
    website: "https://www.udel.edu", image: IMG.hero,
    tags: ["Blue Hens", "Research", "CAA", "Engineering"],
    strongPrograms: ["Engineering", "Business", "Nursing", "Communications", "Agriculture"],
    earlyAction: "11-01", regularDecision: "01-15",
  },
];
